# App
spring.application.name=smart-uni-api
server.port=8080

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=smart_uni_db

# Logging
logging.level.org.springframework=INFO
logging.level.com.smartuni.api=DEBUG